// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 10.0.0.0
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>

namespace KontourApp.Resources.Localization {
    using System;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KontourApp.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        internal static string ShowFolders {
            get {
                return ResourceManager.GetString("ShowFolders", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        internal static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        internal static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        internal static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        internal static string DecreaseTreeWidth {
            get {
                return ResourceManager.GetString("DecreaseTreeWidth", resourceCulture);
            }
        }
        
        internal static string IncreaseTreeWidth {
            get {
                return ResourceManager.GetString("IncreaseTreeWidth", resourceCulture);
            }
        }
        
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        internal static string DrivesFound {
            get {
                return ResourceManager.GetString("DrivesFound", resourceCulture);
            }
        }
        
        internal static string CannotAccessPath {
            get {
                return ResourceManager.GetString("CannotAccessPath", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string FilesDisplay {
            get {
                return ResourceManager.GetString("FilesDisplay", resourceCulture);
            }
        }
        
        internal static string FilesTotal {
            get {
                return ResourceManager.GetString("FilesTotal", resourceCulture);
            }
        }
        
        internal static string AlreadyInFavorites {
            get {
                return ResourceManager.GetString("AlreadyInFavorites", resourceCulture);
            }
        }
        
        internal static string AddedToFavorites {
            get {
                return ResourceManager.GetString("AddedToFavorites", resourceCulture);
            }
        }
        
        internal static string RemovedFromFavorites {
            get {
                return ResourceManager.GetString("RemovedFromFavorites", resourceCulture);
            }
        }
        
        internal static string NoPreviewAudio {
            get {
                return ResourceManager.GetString("NoPreviewAudio", resourceCulture);
            }
        }
        
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        internal static string LocatingFolder {
            get {
                return ResourceManager.GetString("LocatingFolder", resourceCulture);
            }
        }
        
        internal static string LocatedTo {
            get {
                return ResourceManager.GetString("LocatedTo", resourceCulture);
            }
        }
        
        internal static string ScrollEventNotSubscribed {
            get {
                return ResourceManager.GetString("ScrollEventNotSubscribed", resourceCulture);
            }
        }
        
        internal static string CannotLocateFolder {
            get {
                return ResourceManager.GetString("CannotLocateFolder", resourceCulture);
            }
        }
        
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
    }
}
